### ISSUE TITLE
Extended export functionalities

### ISSUE THREAD

**Issue by ponlawat-w** [ponlawat-w/moodle-datafield_timetable#3]
Continued from #1 
- Allow export for student, not just teacher
- Put into Word files, A4.

**Comment by donhinkelman** [comment]
Thank you, Mo. I will try to install and test with students tomorrow.

**Comment by ponlawat-w** [comment]
Hi @donhinkelman, I have added more export functionality that allows student who owns that database record to export there data in the module.
Due to current technical limitation, when they click at "export my printable data" it will open a new raw page that allow students to **_manually copy and paste the content to Microsoft Word_**.

Please open a new issue if you prefer any further improvement.

(Screenshots)
![image](https://user-images.githubusercontent.com/15243484/176593011-29b1af20-02d6-49e9-b098-27ded27922e3.png)

　　　↓

![image](https://user-images.githubusercontent.com/15243484/176593178-5228fb28-d5b0-4fcc-b34b-92b0e1633f51.png)

**Comment by donhinkelman** [comment]
Thank you!
